steps:
  # Reservations
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-central2-docker.pkg.dev/silken-impulse-459518-f6/reservations/production',
        '-f',
        'apps/reservations/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-central2-docker.pkg.dev/silken-impulse-459518-f6/reservations/production',
      ]

  # Auth
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-central2-docker.pkg.dev/silken-impulse-459518-f6/auth/production',
        '-f',
        'apps/auth/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-central2-docker.pkg.dev/silken-impulse-459518-f6/auth/production',
      ]

  # Notifications
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-central2-docker.pkg.dev/silken-impulse-459518-f6/notifications/production',
        '-f',
        'apps/notifications/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-central2-docker.pkg.dev/silken-impulse-459518-f6/notifications/production',
      ]

  # Payments
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-central2-docker.pkg.dev/silken-impulse-459518-f6/payments/production',
        '-f',
        'apps/payments/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-central2-docker.pkg.dev/silken-impulse-459518-f6/payments/production',
      ]
options:
  logging: CLOUD_LOGGING_ONLY
